var flag_dictionary = {
    'ad.png': 'Andorra',
    'ae.png': 'United Arab Emirates',
    'af.png': 'Afghanistan',
    'ag.png': 'Antigua and Barbuda',
    'ai.png': 'Anguilla',
    'al.png': 'Albania',
    'am.png': 'Armenia',
    'ao.png': 'Angola',
    'aq.png': 'Antarctica',
    'ar.png': 'Argentina',
    'as.png': 'American Samoa',
    'at.png': 'Austria',
    'au.png': 'Australia',
    'aw.png': 'Aruba',
    'ax.png': 'Aland Islands',
    'az.png': 'Azerbaijan',
    'ba.png': 'Bosnia and Herzegovina',
    'bb.png': 'Barbados',
    'bd.png': 'Bangladesh',
    'be.png': 'Belgium',
    'bf.png': 'Burkina Faso',
    'bg.png': 'Bulgaria',
    'bh.png': 'Bahrain',
    'bi.png': 'Burundi',
    'bj.png': 'Benin',
    'bl.png': 'Saint Barthelemy',
    'bm.png': 'Bermuda',
    'bn.png': 'Brunei',
    'bo.png': 'Bolivia',
    'bq.png': 'Caribbean Netherlands',
    'br.png': 'Brazil',
    'bs.png': 'The Bahamas',
    'bt.png': 'Bhutan',
    'bv.png': 'Bouvet Island',
    'bw.png': 'Botswana',
    'by.png': 'Belarus',
    'bz.png': 'Belize',
    'ca.png': 'Canada',
    'cc.png': 'Cocos Islands',
    'cd.png': 'Democratic Republic of the Congo',
    'cf.png': 'Central African Republic',
    'cg.png': 'Republic of the Congo',
    'ch.png': 'Switzerland',
    'ci.png': 'Cote d\'Ivoire',
    'ck.png': 'Cook Islands',
    'cl.png': 'Chile',
    'cm.png': 'Cameroon',
    'cn.png': 'China',
    'co.png': 'Colombia',
    'cr.png': 'Costa Rica',
    'cu.png': 'Cuba',
    'cv.png': 'Cabo Verde',
    'cw.png': 'Curacao',
    'cx.png': 'Christmas Island',
    'cy.png': 'Cyprus',
    'cz.png': 'Czechia',
    'de.png': 'Germany',
    'dj.png': 'Djibouti',
    'dk.png': 'Denmark',
    'dm.png': 'Dominica',
    'do.png': 'Dominican Republic',
    'dz.png': 'Algeria',
    'ec.png': 'Ecuador',
    'ee.png': 'Estonia',
    'eg.png': 'Egypt',
    'eh.png': 'Western Sahara',
    'er.png': 'Eritrea',
    'es.png': 'Spain',
    'et.png': 'Ethiopia',
    'fi.png': 'Finland',
    'fj.png': 'Fiji',
    'fk.png': 'Falkland Islands',
    'fm.png': 'Micronesia',
    'fo.png': 'Faroe Islands',
    'fr.png': 'France',
    'ga.png': 'Georgia',
    'gb-eng.png': 'England',
    'gb-nir.png': 'Northern Ireland',
    'gb-sct.png': 'Scotland',
    'gb-wls.png': 'Wales',
    'gb.png': 'United Kingdom',
    'gd.png': 'Grenada',
    'ge.png': 'Georgia',
    'gf.png': 'French Guiana',
    'gg.png': 'Guernsey',
    'gh.png': 'Ghana',
    'gi.png': 'Gibraltar',
    'gl.png': 'Greenland',
    'gm.png': 'The Gambia',
    'gn.png': 'Guinea',
    'gp.png': 'Guadeloupe',
    'gq.png': 'Equatorial Guinea',
    'gr.png': 'Greece',
    'gs.png': 'South Georgia',
    'gt.png': 'Guatemala',
    'gu.png': 'Guam',
    'gw.png': 'Guinea-Bissau',
    'gy.png': 'Guyana',
    'hk.png': 'Hong Kong',
    'hm.png': 'Heard and McDonald Islands',
    'hn.png': 'Honduras',
    'hr.png': 'Croatia',
    'ht.png': 'Haiti',
    'hu.png': 'Hungary',
    'id.png': 'Indonesia',
    'ie.png': 'Ireland',
    'il.png': 'Israel',
    'im.png': 'Isle of Man',
    'in.png': 'India',
    'io.png': 'British Indian Ocean Territory',
    'iq.png': 'Iraq',
    'ir.png': 'Iran',
    'is.png': 'Iceland',
    'it.png': 'Italy',
    'je.png': 'Jersey',
    'jm.png': 'Jamaica',
    'jo.png': 'Jordan',
    'jp.png': 'Japan',
    'ke.png': 'Kenya',
    'kg.png': 'Kyrgyzstan',
    'kh.png': 'Cambodia',
    'ki.png': 'Kiribati',
    'km.png': 'Comoros',
    'kn.png': 'Saint Kitts and Nevis',
    'kp.png': 'North Korea',
    'kr.png': 'South Korea',
    'kw.png': 'Kuwait',
    'ky.png': 'Cayman Islands',
    'kz.png': 'Kazakhstan',
    'la.png': 'Laos',
    'lb.png': 'Lebanon',
    'lc.png': 'Saint Lucia',
    'li.png': 'Liechtenstein',
    'lk.png': 'Sri Lanka',
    'lr.png': 'Liberia',
    'ls.png': 'Lesotho',
    'lt.png': 'Lithuania',
    'lu.png': 'Luxembourg',
    'lv.png': 'Latvia',
    'ly.png': 'Libya',
    'ma.png': 'Morocco',
    'mc.png': 'Monaco',
    'md.png': 'Moldova',
    'me.png': 'Montenegro',
    'mf.png': 'Saint Martin',
    'mg.png': 'Madagascar',
    'mh.png': 'Marshall Islands',
    'mk.png': 'North Macedonia',
    'ml.png': 'Mali',
    'mm.png': 'Myanmar',
    'mn.png': 'Mongolia',
    'mo.png': 'Macao',
    'mp.png': 'Northern Mariana Islands',
    'mq.png': 'Martinique',
    'mr.png': 'Mauritania',
    'ms.png': 'Montserrat',
    'mt.png': 'Malta',
    'mu.png': 'Mauritius',
    'mv.png': 'Maldives',
    'mw.png': 'Malawi',
    'mx.png': 'Mexico',
    'my.png': 'Malaysia',
    'mz.png': 'Mozambique',
    'na.png': 'Namibia',
    'nc.png': 'New Caledonia',
    'ne.png': 'Niger',
    'nf.png': 'Norfolk Island',
    'ng.png': 'Nigeria',
    'ni.png': 'Nicaragua',
    'nl.png': 'Netherlands',
    'no.png': 'Norway',
    'np.png': 'Nepal',
    'nr.png': 'Nauru',
    'nu.png': 'Niue',
    'nz.png': 'New Zealand',
    'om.png': 'Oman',
    'pa.png': 'Paraguay',
    'pe.png': 'Peru',
    'pf.png': 'French Polynesia',
    'pg.png': 'Papua New Guinea',
    'ph.png': 'Philippines',
    'pk.png': 'Pakistan',
    'pl.png': 'Poland',
    'pm.png': 'Saint Pierre and Miquelon',
    'pn.png': 'Pitcairn Islands',
    'pr.png': 'Puerto Rico',
    'ps.png': 'Palestine',
    'pt.png': 'Portugal',
    'pw.png': 'Palau',
    'py.png': 'Paraguay',
    'qa.png': 'Qatar',
    're.png': 'Reunion',
    'ro.png': 'Romania',
    'rs.png': 'Serbia',
    'ru.png': 'Russia',
    'rw.png': 'Rwanda',
    'sa.png': 'Saudi Arabia',
    'sb.png': 'Solomon Islands',
    'sc.png': 'Seychelles',
    'sd.png': 'Sudan',
    'se.png': 'Sweden',
    'sg.png': 'Singapore',
    'sh.png': 'Saint Helena',
    'si.png': 'Slovenia',
    'sj.png': 'Svalbard and Jan Mayen',
    'sk.png': 'Slovakia',
    'sl.png': 'Sierra Leone',
    'sm.png': 'San Marino',
    'sn.png': 'Senegal',
    'so.png': 'Somalia',
    'sr.png': 'Suriname',
    'ss.png': 'South Sudan',
    'st.png': 'Sao Tome',
    'sv.png': 'El Salvador',
    'sx.png': 'Sint Maarten',
    'sy.png': 'Syria',
    'sz.png': 'Eswatini',
    'tc.png': 'Turks and Caicos Islands',
    'td.png': 'Chad',
    'tf.png': 'French Southern Territories',
    'tg.png': 'Togo',
    'th.png': 'Thailand',
    'tj.png': 'Tajikistan',
    'tk.png': 'Tokelau',
    'tl.png': 'Timor-Leste',
    'tm.png': 'Turkmenistan',
    'tn.png': 'Tunisia',
    'to.png': 'Tonga',
    'tr.png': 'Turkey',
    'tt.png': 'Trinidad and Tobago',
    'tv.png': 'Tuvalu',
    'tw.png': 'Taiwan',
    'tz.png': 'Tanzania',
    'ua.png': 'Ukraine',
    'ug.png': 'Uganda',
    'um.png': 'United States Minor Outlying Islands',
    'us.png': 'United States',
    'uy.png': 'Uruguay',
    'uz.png': 'Uzbekistan',
    'va.png': 'Vatican City',
    'vc.png': 'Saint Vincent and the Grenadines',
    've.png': 'Venezuela',
    'vg.png': 'British Virgin Islands',
    'vi.png': 'U.S. Virgin Islands',
    'vn.png': 'Vietnam',
    'vu.png': 'Vanuatu',
    'wf.png': 'Wallis and Futuna',
    'ws.png': 'Samoa',
    'xk.png': 'Kosovo',
    'ye.png': 'Yemen',
    'yt.png': 'Mayotte',
    'za.png': 'South Africa',
    'zm.png': 'Zambia',
    'zw.png': 'Zimbabwe'
}

const gallery = document.getElementById('gallery');
let imageCount = 0;
let currentLine = null;

function show_flags() {
    for (const key in flag_dictionary) {
        if (flag_dictionary.hasOwnProperty(key)) {
            const imagePath = 'flags/' + key;
            const countryName = flag_dictionary[key];

            const imageElement = document.createElement('img');
            imageElement.src = imagePath;

            const captionElement = document.createElement('div');
            captionElement.textContent = countryName;
            captionElement.className = 'caption';

            const imageContainer = document.createElement('div');
            imageContainer.className = 'image-container';
            imageContainer.appendChild(imageElement);
            imageContainer.appendChild(captionElement);

            if (imageCount % 4 === 0) {
                currentLine = document.createElement('div');
                currentLine.className = 'image-line';
                gallery.appendChild(currentLine);
            }

            currentLine.appendChild(imageContainer);
            imageCount++;
        }
    }
}
show_flags()